-- ON DONNE LES DROITS A L'UTILISATEUR POUR QU4ON PUISSE LE SUPPRIMER AU CAS OU IL EXISTE
-- CA PERMET DE REMPLACER L'EXPRESSION [IF EXISTS] QUI REQUIERE UNE VERSION RECENTE DE MYSQL
GRANT ALL PRIVILEGES ON AVOTE.* TO 'avote'@'localhost';
DROP USER 'avote'@'localhost';
CREATE USER 'avote'@'localhost' IDENTIFIED BY 'testpass';
GRANT ALL PRIVILEGES ON AVOTE.* TO 'avote'@'localhost';

GRANT ALL PRIVILEGES ON AVOTE_TEST.* TO 'avote_test'@'localhost';
DROP USER 'avote_test'@'localhost';
CREATE USER 'avote_test'@'localhost' IDENTIFIED BY 'testpass';
GRANT ALL PRIVILEGES ON AVOTE_TEST.* TO 'avote_test'@'localhost';